#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Xamarin.Braintree.Android.Test.Resource", IsApplication=true)]

namespace Xamarin.Braintree.Android.Test
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int appTheme = 2130771971;
			
			// aapt resource value: 0x7f01000a
			public const int buyButtonAppearance = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int buyButtonHeight = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int buyButtonText = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int buyButtonWidth = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int environment = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int fragmentMode = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int fragmentStyle = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public const int maskedWalletDetailsBackground = 2130771981;
			
			// aapt resource value: 0x7f01000f
			public const int maskedWalletDetailsButtonBackground = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int maskedWalletDetailsButtonTextAppearance = 2130771982;
			
			// aapt resource value: 0x7f01000c
			public const int maskedWalletDetailsHeaderTextAppearance = 2130771980;
			
			// aapt resource value: 0x7f010011
			public const int maskedWalletDetailsLogoImageType = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int maskedWalletDetailsLogoTextColor = 2130771984;
			
			// aapt resource value: 0x7f01000b
			public const int maskedWalletDetailsTextAppearance = 2130771979;
			
			// aapt resource value: 0x7f010012
			public const int windowTransitionStyle = 2130771986;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060005
			public const int wallet_bright_foreground_disabled_holo_light = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int wallet_bright_foreground_holo_dark = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int wallet_bright_foreground_holo_light = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int wallet_dim_foreground_disabled_holo_dark = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int wallet_dim_foreground_holo_dark = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int wallet_dim_foreground_inverse_disabled_holo_dark = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int wallet_dim_foreground_inverse_holo_dark = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int wallet_highlighted_text_holo_dark = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int wallet_highlighted_text_holo_light = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int wallet_hint_foreground_holo_dark = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int wallet_hint_foreground_holo_light = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int wallet_holo_blue_light = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int wallet_link_text_light = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int wallet_primary_text_holo_light = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int wallet_secondary_text_holo_dark = 2131099662;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int adjust_height = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int adjust_width = 2131230721;
			
			// aapt resource value: 0x7f08001d
			public const int android_pay = 2131230749;
			
			// aapt resource value: 0x7f080014
			public const int android_pay_dark = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int android_pay_light = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int android_pay_light_with_border = 2131230742;
			
			// aapt resource value: 0x7f08000d
			public const int book_now = 2131230733;
			
			// aapt resource value: 0x7f080009
			public const int buyButton = 2131230729;
			
			// aapt resource value: 0x7f08000e
			public const int buy_now = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int buy_with = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int buy_with_google = 2131230736;
			
			// aapt resource value: 0x7f080017
			public const int classic = 2131230743;
			
			// aapt resource value: 0x7f080011
			public const int donate_with = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int donate_with_google = 2131230738;
			
			// aapt resource value: 0x7f080018
			public const int google_wallet_classic = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int google_wallet_grayscale = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int google_wallet_monochrome = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int grayscale = 2131230747;
			
			// aapt resource value: 0x7f080003
			public const int holo_dark = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int holo_light = 2131230724;
			
			// aapt resource value: 0x7f080013
			public const int logo_only = 2131230739;
			
			// aapt resource value: 0x7f08000b
			public const int match_parent = 2131230731;
			
			// aapt resource value: 0x7f08001c
			public const int monochrome = 2131230748;
			
			// aapt resource value: 0x7f08001f
			public const int myButton = 2131230751;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int production = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int sandbox = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int selectionDetails = 2131230730;
			
			// aapt resource value: 0x7f08001e
			public const int slide = 2131230750;
			
			// aapt resource value: 0x7f080007
			public const int strict_sandbox = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int test = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int wrap_content = 2131230732;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040005
			public const int app_name = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int hello = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int wallet_buy_button_place_holder = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int WalletFragmentDefaultButtonTextAppearance = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int WalletFragmentDefaultDetailsHeaderTextAppearance = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int WalletFragmentDefaultDetailsTextAppearance = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int WalletFragmentDefaultStyle = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int bt_no_activity_animation = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int bt_transparent_activity = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CustomWalletTheme = new int[]
			{
					2130771986};
			
			// aapt resource value: 0
			public const int CustomWalletTheme_windowTransitionStyle = 0;
			
			public static int[] LoadingImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] WalletFragmentOptions = new int[]
			{
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int WalletFragmentOptions_appTheme = 0;
			
			// aapt resource value: 1
			public const int WalletFragmentOptions_environment = 1;
			
			// aapt resource value: 3
			public const int WalletFragmentOptions_fragmentMode = 3;
			
			// aapt resource value: 2
			public const int WalletFragmentOptions_fragmentStyle = 2;
			
			public static int[] WalletFragmentStyle = new int[]
			{
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 3
			public const int WalletFragmentStyle_buyButtonAppearance = 3;
			
			// aapt resource value: 0
			public const int WalletFragmentStyle_buyButtonHeight = 0;
			
			// aapt resource value: 2
			public const int WalletFragmentStyle_buyButtonText = 2;
			
			// aapt resource value: 1
			public const int WalletFragmentStyle_buyButtonWidth = 1;
			
			// aapt resource value: 6
			public const int WalletFragmentStyle_maskedWalletDetailsBackground = 6;
			
			// aapt resource value: 8
			public const int WalletFragmentStyle_maskedWalletDetailsButtonBackground = 8;
			
			// aapt resource value: 7
			public const int WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance = 7;
			
			// aapt resource value: 5
			public const int WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance = 5;
			
			// aapt resource value: 10
			public const int WalletFragmentStyle_maskedWalletDetailsLogoImageType = 10;
			
			// aapt resource value: 9
			public const int WalletFragmentStyle_maskedWalletDetailsLogoTextColor = 9;
			
			// aapt resource value: 4
			public const int WalletFragmentStyle_maskedWalletDetailsTextAppearance = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
